# TODO: Translation updated at 2024-12-12 19:26

translate german strings:

    # game/options.rpy:15
    old "Pine Point: Insomniac"
    new "Pine Point: Insomniac"

    # game/options.rpy:32
    old "{font=roboto_condensed_bold.ttf}{i}Pine Point: Insomniac{/} is a short, surreal slice-of-life visual novel following Nil, a severly sleep-deprived slacker, as he tries to survive the day at work with his best friend, Dimitri.{para}This game was created as a proof-of-concept for {i}Pine Point{/}.{para}Note that the events that occur in this game may not remain canon if the series continues.\n\nSupport the creator & series via: {a=https://www.patreon.com/zeddyzi}Patreon{/a} | {a=https://zeddyzi-shop.fourthwall.com/en-cad/}Merch{/a} | {a=https://www.youtube.com/channel/UCVDxozAfpwnZuySPPLLMuGQ}YouTube{/a}{para}{a=https://aylins.carrd.co}Aylin Scherer - Deutsch{/a}{para}{a=https://nhungtran.carrd.co/}Nhung Tran - Tieng Viet{/}{para}{a=https://thisisstefaniafiocchi.carrd.co/}Stefanía Fiocchi - Español{/}\n\n{u}DISCLAIMER:{/u} All characters, settings and events are fictional works.{para}Any resemblance to real life events/people and/or other media is unintentional or coincidental.\n\n{color=#ff0}WARNING{/color}{para}- Contains some eye strain and swearing{para}- Mentions of drug use, death, and emetophobia{/font}"
    new "{font=roboto_condensed_bold.ttf}{i}Pine Point: Insomniac{/} ist ein kurzes, surreales, textbasiertes Spiel, welches von Nil, einem schlaflosen Faulpelz handelt, der versucht, den Arbeitstag mit seinem besten Freund Dimitri zu überleben.{para}Dieses Spiel wurde als Machbarkeitsnachweis für {i}Pine Point{/} gemacht.{para}Die Ereignisse in diesem Spiel bleiben eventuell nicht im Kanon, falls diese Serie fortgesetzt werden sollte.\n\nUnterstütze den Macher & die Serie via: {a=https://www.patreon.com/zeddyzi}Patreon{/a} | {a=https://zeddyzi-shop.fourthwall.com/en-cad/}Merch{/a} | {a=https://www.youtube.com/channel/UCVDxozAfpwnZuySPPLLMuGQ}YouTube{/a}{para}{a=https://aylins.carrd.co}Aylin Scherer - Deutsch{/a}{para}{a=https://nhungtran.carrd.co/}Nhung Tran - Tieng Viet{/}{para}{a=https://thisisstefaniafiocchi.carrd.co/}Stefanía Fiocchi - Español{/}\n\n{u}ACHTUNG:{/u} Alle Figuren, Orte und Ereignisse sind ausgedacht.{para}Ähnlichkeiten zu realen Geschehnissen/Menschen und/oder Medien sind nicht beabsichtigt.\n\n{color=#ff0}WARNUNG{/color}{para}- Beinhaltet Überanstrengung der Augen und Fluchen{para}- Erwähnungen von Drogen, Tod und Emetophobie{/font}"